server {

    server_name ibeh.website www.ibeh.website;

    location / {
        proxy_pass http://localhost:5000;

    location /health {
        proxy_pass http://localhost:5000/health;
    }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ibeh.website/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ibeh.website/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

